name: Java CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger on push to main branch
  pull_request:
    branches:
      - main  # Trigger on pull request to main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Define the operating system for the job

    steps:
  - uses: actions/checkout@v4
  - name: Set up JDK 11 for x64
    uses: actions/setup-java@v4
    with:
      java-version: '11'
      distribution: 'temurin'
      architecture: x64

      - name: Build with Maven
        run: mvn clean install  # Maven command to build your project

      - name: Run Tests with Maven
        run: mvn test  # Run tests using Maven
      
      # Optionally deploy to a server or perform additional steps here
      # - name: Deploy to Production
      #   run: ./deploy.sh
