name: Java Selenium CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v4

    # Step 2: Set up Java (Temurin is the successor to AdoptOpenJDK)
    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin' # Java distribution
        java-version: '11'      # Java version (adjust if needed)

    # Step 3: Cache Maven dependencies
    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-m2

    # Step 4: Build the project using Maven
    - name: Build with Maven
      run: mvn clean install

    # Step 5: Run Selenium tests
    - name: Run Selenium tests
      run: mvn test

    # Optional: Upload test results or logs as artifacts (if needed)
    - name: Upload Test Results
      if: always() # Always run this step to capture logs even if tests fail
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: target/surefire-reports/*.xml
